### ISSUE TITLE
How to run this on python 3?

### ISSUE THREAD

**Issue by psychoshawny** [miguelgrinberg/REST-tutorial#10]
Hello Miguel.

I know you stated in the readme to run this on python 2. But is there any way I can modify the program to run on python 3?

Currently, it produces this error when I run it using python 3 (after entering the credentials in the dialog box) : 

    Traceback (most recent call last):
      File "/home/shawn/.virtualenvs/flaskp3/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
        return self.wsgi_app(environ, start_response)
      File "/home/shawn/.virtualenvs/flaskp3/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
        response = self.make_response(self.handle_exception(e))
      File "/home/shawn/.virtualenvs/flaskp3/lib/python3.4/site-packages/flask_restful/__init__.py", line 263, in error_router
        return original_handler(e)
      File "/home/shawn/.virtualenvs/flaskp3/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/home/shawn/.virtualenvs/flaskp3/lib/python3.4/site-packages/flask/_compat.py", line 32, in reraise
        raise value.with_traceback(tb)
      File "/home/shawn/.virtualenvs/flaskp3/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/home/shawn/.virtualenvs/flaskp3/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/home/shawn/.virtualenvs/flaskp3/lib/python3.4/site-packages/flask_restful/__init__.py", line 263, in error_router
        return original_handler(e)
      File "/home/shawn/.virtualenvs/flaskp3/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/home/shawn/.virtualenvs/flaskp3/lib/python3.4/site-packages/flask/_compat.py", line 32, in reraise
        raise value.with_traceback(tb)
      File "/home/shawn/.virtualenvs/flaskp3/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/home/shawn/.virtualenvs/flaskp3/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/home/shawn/.virtualenvs/flaskp3/lib/python3.4/site-packages/flask_restful/__init__.py", line 435, in wrapper
        return self.make_response(data, code, headers=headers)
      File "/home/shawn/.virtualenvs/flaskp3/lib/python3.4/site-packages/flask_restful/__init__.py", line 452, in make_response
        resp = self.representations[mediatype](data, *args, **kwargs)
      File "/home/shawn/.virtualenvs/flaskp3/lib/python3.4/site-packages/flask_restful/representations/json.py", line 24, in output_json
        dumped = dumps(data, **local_settings)
      File "/usr/lib/python3.4/json/__init__.py", line 237, in dumps
        **kw).encode(obj)
      File "/usr/lib/python3.4/json/encoder.py", line 194, in encode
        chunks = list(chunks)
      File "/usr/lib/python3.4/json/encoder.py", line 422, in _iterencode
        yield from _iterencode_dict(o, _current_indent_level)
      File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
        yield from chunks
      File "/usr/lib/python3.4/json/encoder.py", line 429, in _iterencode
        o = _default(o)
      File "/usr/lib/python3.4/json/encoder.py", line 173, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    TypeError: <map object at 0x7f81d1c50e10> is not JSON serializable

And the response I get in the browser in the web console is `ajax error 500`.

**Comment by miguelgrinberg** [comment]
@psychoshawny I have fixed both `rest-server.py` and `rest-server-v2.py` to work with Py3. Note there are new requirements, I've added `six`.

**Comment by psychoshawny** [comment]
Wow! Thank you for the prompt reply & fixing the issue!
